### ISSUE TITLE
Arrow slide next prev with slideAnimation

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo-app#3]
Right now, all swiping/sliding is send to the deck without any inner slide animation (option "slideAnimation"). This makes sense when the slides are slides but would be cooler to ask for animation when the arrows are use

But to realize this enhancement, the app should be aware of the content of the deck, which is not yet the case except the length of the presentation

Somehow related enhancement with https://github.com/fluster/deckdeckgo-app/issues/2

**Comment by peterpeterparker** [comment]
The app is/shoud be now aware of what's in the deck, as the slides definition is now exchanged (I should check if the attributes too)...anyhow that should be possible

**Comment by peterpeterparker** [comment]
Actually no, nothing more should be exchanged. On click on the buttons, the transition in the app should not happens directly but only happens if the deck says to do so

**Comment by peterpeterparker** [comment]
@Dellos7 your feature request has been implemented, thx for pinging me about it ;)

If you want to reflect the change in your presentation, you will need to modify the file `remoteControl.js` as in the following commit https://github.com/deckgo/deckdeckgo-starter/commit/f17107de2fd69f716e7fec8abe945100b07b6034#diff-f664793e9b8af8de62737da713cd808e

**Comment by Dellos7** [comment]
> @Dellos7 your feature request has been implemented and the new version of the app has been deployed, thx for pinging me about it ;)
> 
> If you want to reflect the change in your presentation, you will need to modify the file `remoteControl.js` as in the following commit [deckgo/deckdeckgo-starter@f17107d#diff-f664793e9b8af8de62737da713cd808e](https://github.com/deckgo/deckdeckgo-starter/commit/f17107de2fd69f716e7fec8abe945100b07b6034#diff-f664793e9b8af8de62737da713cd808e)

Thank you!! I have tried it right now and it works very well. 

deckdeckgo becoming my first presentation tool option in 3, 2, 1... 🙄

**Comment by peterpeterparker** [comment]
Awesome, thx for the feedback @Dellos7, cool to hear it worked out 👍 

I spent hours implementing a complicated code to solve this till I finally figured out it could be solved just by a couple of changes 😂

It made my day to hear you like DeckDeckGo ❤️ Ping me for any ideas!
